I'm sorry, but an uncaught exception occurred.

Executing ATL code at game/script.rpy:48
  File "game/script.rpy", line 37, in script
    show unspeakable_horror:
Exception: ATL appears to be in an infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 37, in script
    show unspeakable_horror:
  File "/Users/arajo/renpy_games/renpy/ast.py", line 1183, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Users/arajo/renpy_games/renpy/ast.py", line 1153, in show_imspec
    atl=atl)
  File "/Users/arajo/renpy_games/renpy/exports.py", line 717, in show
    sls.add(layer, img, key, zorder, behind, at_list=at_list, name=name, atl=atl, default_transform=default_transform, transient=transient)
  File "/Users/arajo/renpy_games/renpy/display/core.py", line 1078, in add
    thing._show()
  File "/Users/arajo/renpy_games/renpy/display/transform.py", line 1048, in _show
    super(ATLTransform, self)._show()
  File "/Users/arajo/renpy_games/renpy/display/transform.py", line 1014, in _show
    self.update_state()
  File "/Users/arajo/renpy_games/renpy/display/transform.py", line 1036, in update_state
    fr = self.execute(self, self.st, self.at)
  File "/Users/arajo/renpy_games/renpy/atl.py", line 564, in execute
    action, arg, pause = block.execute(trans, timebase, self.atl_state, events)
  File "/Users/arajo/renpy_games/renpy/atl.py", line 771, in execute
    action, arg, pause = stmt.execute(trans, target - start, child_state, events)
  File "/Users/arajo/renpy_games/renpy/atl.py", line 1352, in execute
    action, arg, pause = i.execute(trans, st, istate, events)
  File "/Users/arajo/renpy_games/renpy/atl.py", line 799, in execute
    raise Exception("ATL appears to be in an infinite loop.")
Exception: ATL appears to be in an infinite loop.

Darwin-18.7.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
derek 1.0
Tue Sep 22 12:25:51 2020
